var i18n = {
	"completed": "completado",
	"process": "en proceso",

	"module activated" : "m&oacute;dulo activado",
	"module deactivated" : "m&oacute;dulo desactivado",
	"modules deactivated": "m&oacute;dulos desactivados",

	"usersagent" : "usuarios",
	"user" : "usuarios",
    "user:create: success" : "creaci&oacute;n usuario/s: correcto",
    "user:read: success" : "lectura usuario/s: correcto",
    "user:delete: success" : "eliminaci&oacute;n usuario/s: correcto",
    "user:update: success" : "actualizaci&oacute;n usuario: correcto",

	"connecting to the system" : "conectando con el sistema",
	"connected to the system" : "conectado al sistema",
	"disconnecting": 'desconectando',
	"disconnected" : "desconectado",
	"loading" : "cargando",

	"there is an error with the session": "existe un error con la sesi&oacute;n",
	"please contact your admin": "contacte con su administrador",

	"field required": "Campo obligatorio",
	"this value must be integer": "No es num&eacute;rico",
	"password doesn't match": "Contrase&ntilde;a incorrecta",
    "browse": "Seleccionar...",
    "Upload a file": "Subir archivo",
    "Module inactive": "M&oacute;dulo inactivo",
    "this value is not allowed": "Valor incorrecto",
    "Welcome to g3suser": "Bienvenido a g3suser",
    "Monday": "Lunes",
    "Tuesday": "Martes",
    "Wenesday": "Mi&eacute;rcoles",
    "Thursday": "Jueves",
    "Friday": "Viernes",
    "Saturday": "S&aacute;bado",
    "Sunday": "Domingo",
    "Delete user": "Eliminar usuario",
    "Cancel": "Cancelar",
    "Ok": "Aceptar",
    "Delete": "Eliminar",
    "Update user": "Actualizar usuario",
    "users selected": "los usuarios seleccionados"
};