#!/usr/bin/env python
# -*- coding: utf-8 -*-

CREATE_DATABASE = """CREATE DATABASE %s CHARACTER SET utf8 COLLATE utf8_bin"""
SHOW_TABLES = """SHOW TABLES"""
CREATE_TABLE_PREFIX = """CREATE TABLE %s """
CREATE_TABLE_SUFIX = " CHARACTER SET utf8 COLLATE utf8_bin"
READ_DATA = '''SELECT * FROM %s WHERE %s = "%s"'''
INSERT_DOCUMENT_PREFIX = """INSERT INTO %s """
DELETE_DOCS = '''DELETE FROM %s'''
DELETE_SPEC_DOC = '''DELETE FROM %s WHERE %s = "%s"'''
UPDATE_DATA_PREFIX = '''UPDATE %s SET '''


#CREATE_TABLE = """CREATE TABLE %s (id int AUTO_INCREMENT PRIMARY KEY,last varchar(255) CHARACTER SET utf8 COLLATE utf8_bin,first varchar(255)) """